---
title: Jekyll Personal Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
params:
  homepage:
    title: Sourav Adhikari
    subtitle: Personal website and blog
    image: "/assets/images/myAvatar_HB.png"
  pageNotFound:
    title: This page does not exist
    image: "/assets/images/myAvatar_HB.png"
